[[collection]]
type = "card"
title = "ml-repertoire"
link = ""
content = "This repertoire of mine keeps the main concepts I've familiarized myself with in the field of AI"
tags = ["NN", "XAI", "ML"]

